baseURL = "https://homieiot.github.io"
languageCode = "en-us"
title = "The Homie convention"
description = "An MQTT convention"
theme = "b4"
pygmentsUseClasses = true
PygmentsCodeFences = true

[params]
  editurl = "https://github.com/homieiot/convention-website/edit/master/content/"
  repourl = "https://github.com/homieiot/convention"
  repotitle = "homieiot/convention"
  reposlug = "homieiot/convention"
  enableGitInfo = true
[markup.goldmark.renderer]
  unsafe = true

[permalinks]
	offline = ":filename"

[menu]

  [[menu.main]]
    name = "Overview"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Specification"
    url = "/specification/"
    weight = 2

  [[menu.main]]
    name = "Extensions"
    url = "/extensions/"
    weight = 3
    
  [[menu.main]]
    name = "Implementations"
    url = "/implementations/"
    weight = 4

  [[menu.main]]
    name = "Get involved"
    url = "/get_involved/"
    weight = 5

  [[menu.main]]
    name = "Tools"
    url = "/tools/"
    weight = 6
